@extends('layouts.main')

@section('title') Home @endsection

@section('content')

    <div class="container mt-5">
        <h3>Benvenuti sul nostro sito!</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab libero esse quis ducimus omnis illo eos aliquam modi eius molestiae tempora ex assumenda consectetur alias corporis, voluptates nulla inventore cumque eaque commodi expedita error placeat! Totam obcaecati eligendi impedit perferendis tempore assumenda quis, corrupti ducimus illum, nesciunt perspiciatis illo neque. Reprehenderit est dolorum qui. Harum eius quia expedita dolorem error, tempore architecto dicta magni dolores placeat, doloremque quas laudantium inventore vero minus autem ad nesciunt, excepturi facilis? Consectetur aliquid expedita esse, non omnis perspiciatis hic quae? Sint quas atque, ea quaerat veritatis voluptatibus libero officia aliquid voluptate expedita corrupti impedit consequatur unde facilis saepe numquam soluta magni tempore magnam laborum? Voluptatum, neque quod! Non quisquam odio ipsum iure fugiat similique aliquid, accusamus impedit nobis vero? Sunt neque accusantium possimus dolorem reiciendis soluta molestiae voluptatum velit quisquam explicabo tempora illum magnam maxime quam laboriosam ipsa quasi, nulla placeat iste nihil. Perferendis ipsam, itaque cum ipsum sit odio voluptate iure, vitae quibusdam aliquam earum numquam molestias velit? Iste, provident atque, recusandae non tenetur, fugit doloremque possimus dolore amet soluta in commodi incidunt illo nostrum illum blanditiis nemo. Exercitationem aut asperiores natus beatae velit dolores, totam ratione pariatur reprehenderit illum dolore rerum veniam tempora laudantium, nostrum, hic obcaecati dolorum. Nisi sint nostrum neque sed quae, modi, consectetur reprehenderit molestiae eveniet id repellendus praesentium architecto! Dolorum praesentium cum aliquam placeat earum dicta a, dolore sequi ratione? Animi, modi? Molestias possimus atque sit nostrum deserunt! Incidunt, commodi voluptatum! Totam ipsam assumenda iste eum ab illo id mollitia est quia officiis, laudantium deleniti error molestiae iure. Enim non voluptatum quia tempore rerum! Voluptates doloremque assumenda eum. Nobis, voluptate. Deserunt doloremque nihil aut ipsum alias cum eos magnam, nisi odio, ullam enim. Fugiat, architecto rerum ex fuga optio saepe alias, molestias, quasi beatae nobis magni ipsam accusantium.</p>
    </div>
    
@endsection